### ISSUE TITLE
Hackerrank Interview Prep Kit's Recursion and Backtracking Java Solutions 

### ISSUE THREAD

**Issue by dhruvilgandhi** [Ketan2010/java-codes#20]
Would like to add 4 Java Solutions of Hackerrank Interview Prep Kit's Recursion and Backtracking Java Solutions.
Link of the problems: https://www.hackerrank.com/interview/interview-preparation-kit/recursion-backtracking/challenges
PR: #19 
@Ketan2010  Please consider this for HacktoberFest 2021

**Comment by Ketan2010** [comment]
Sure @dhruvilgandhi 
Thanks for your contribution!
